# Generated by Django 5.0.1 on 2024-02-22 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[(1, 'муж.'), (2, 'жен.')], default=1, max_length=1),
        ),
    ]
