# Generated by Django 5.0.1 on 2024-02-25 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[(1, 'муж.'), (2, 'жен.')], default=1, max_length=1, null=True),
        ),
    ]
