# Generated by Django 5.0.1 on 2024-03-04 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(0, 'муж.'), (1, 'жен.')], default=0, max_length=1, null=True),
        ),
    ]
