# Generated by Django 5.0.1 on 2024-03-09 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('0', 'Муж.'), ('1', 'Жен.')], default='0', max_length=1, null=True),
        ),
    ]
