# Generated by Django 5.0.1 on 2024-02-25 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_reviewimages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-date']},
        ),
    ]
