first_categories = [
    {'category': 'Женщинам', 'data': '#women', 'id': 'women',
     'products': [{'title': 'Блузки и рубашки', 'url': '#1'},
                  {'title': 'Брюки', 'url': '#2'},
                  {'title': 'Верхняя одежда', 'url': '#3'},
                  {'title': 'Джемперы, водолазки и кардиганы', 'url': '#4'},
                  {'title': 'Джинсы', 'url': '#5'},
                  {'title': 'Комбинезоны', 'url': '#6'},
                  {'title': 'Костюмы', 'url': '#7'},
                  {'title': 'Лонгсливы', 'url': '#8'},
                  {'title': 'Пиджаки, жилеты и жакеты', 'url': '#9'},
                  {'title': 'Платья и сарафаны', 'url': '#10'},
                  {'title': 'Толстовки, свитшоты и худи', 'url': '#11'},
                  {'title': 'Туники', 'url': '#12'},
                  {'title': 'Футболки и топы', 'url': '#13'},
                  {'title': 'Халаты', 'url': '#14'},
                  {'title': 'Шорты', 'url': '#15'},
                  {'title': 'Юбки', 'url': '#16'},
                  {'title': 'Белье', 'url': '#17'},
                  {'title': 'Большие размеры', 'url': '#18'},
                  {'title': 'Будущие мамы', 'url': '#19'},
                  {'title': 'Для высоких', 'url': '#20'},
                  {'title': 'Для невысоких', 'url': '#21'},
                  {'title': 'Одежда для дома', 'url': '#22'},
                  {'title': 'Офис', 'url': '#23'},
                  {'title': 'Пляжная мода', 'url': '#24'},
                  {'title': 'Религиозная', 'url': '#25'},
                  {'title': 'Свадьба', 'url': '#26'},
                  {'title': 'Спецодежда и СИЗы', 'url': '#27'},
                  {'title': 'Подарки женщинам', 'url': '#28'}]},
    {'category': 'Обувь', 'data': '#shoes', 'id': 'shoes', 'products':
        [{'title': 'Детская', 'url': '#1'},
         {'title': 'Для новорожденных', 'url': '#2'},
         {'title': 'Женская', 'url': '#3'},
         {'title': 'Мужская', 'url': '#4'},
         {'title': 'Ортопедическая обувь', 'url': '#5'},
         {'title': 'Аксессуары для обуви', 'url': '#6'}]},
    {'category': 'Детям', 'data': '#kids', 'id': 'kids'},
    {'category': 'Мужчинам', 'data': '#men', 'id': 'men'},
    {'category': 'Дом,', 'data': '#house', 'id': 'house'},
    {'category': 'Новый год', 'data': '#newyear', 'id': 'newyear'},
    {'category': 'Красота', 'data': '#beauty', 'id': 'beauty'},
    {'category': 'Аксессуары', 'data': '#accessories', 'id': 'accessories'},
    {'category': 'Электроника', 'data': '#electronics', 'id': 'electronics'},
    {'category': 'Игрушки', 'data': '#toys', 'id': 'toys'},
    {'category': 'Мебель', 'data': '#furniture', 'id': 'furniture'},
    {'category': 'Товары для взрослых', 'data': '#productsforadult', 'id': 'productsforadult'},
    {'category': 'Продукты', 'data': '#products', 'id': 'products'},
    {'category': 'Бытовая техника', 'data': '#appliances', 'id': 'appliances'},
    {'category': 'Зоотовары', 'data': '#zoo', 'id': 'zoo'},
    {'category': 'Спорт', 'data': '#sport', 'id': 'sport'},
    {'category': 'Автотовары', 'data': '#autoproducts', 'id': 'autoproducts'},
    {'category': 'Книги', 'data': '#books', 'id': 'books'},
    {'category': 'Для ремонта', 'data': '#forrepair', 'id': 'forrepair'},
    {'category': 'Сад и дача', 'data': '#garden', 'id': 'garden'},
    {'category': 'Здоровье', 'data': '#healt', 'id': 'healt'},
    {'category': 'Канцтовары', 'data': '#stationery', 'id': 'stationery'},
    {'category': 'Акции', 'data': '#promotions', 'id': 'promotions'},
]
navbar_list = [
    {'title': 'Доставки', 'img': 'products/images/header/delivery.png', 'alt': 'delivery', 'href': 'products:favorites'},
    {'title': 'Избранное', 'img': 'products/images/header/favorites.png', 'alt': 'favorite', 'href': 'products:favorites'},
    {'title': 'Профиль', 'img': 'products/images/header/profile.png', 'alt': 'profile', 'href': 'products:favorites'},
    {'title': 'Корзина', 'img': 'products/images/header/basket.png', 'alt': 'basket', 'href': 'products:favorites'},
]
