first_categories = [
    {'category': 'Женщины', 'data': '#women', 'id': 'women',
     'products': [{'title': 'Блузки и рубашки', 'url': '#1'},
                  {'title': 'Брюки', 'url': '#2'},
                  {'title': 'Верхняя одежда', 'url': '#3'},
                  {'title': 'Джемперы, водолазки и кардиганы', 'url': '#4'},
                  {'title': 'Джинсы', 'url': '#5'},
                  {'title': 'Комбинезоны', 'url': '#6'},
                  {'title': 'Костюмы', 'url': '#7'},
                  {'title': 'Лонгсливы', 'url': '#8'},
                  {'title': 'Пиджаки, жилеты и жакеты', 'url': '#9'},
                  {'title': 'Платья и сарафаны', 'url': '#10'},
                  {'title': 'Толстовки, свитшоты и худи', 'url': '#11'},
                  {'title': 'Туники', 'url': '#12'},
                  {'title': 'Футболки и топы', 'url': '#13'},
                  {'title': 'Халаты', 'url': '#14'},
                  {'title': 'Шорты', 'url': '#15'},
                  {'title': 'Юбки', 'url': '#16'},
                  {'title': 'Белье', 'url': '#17'},
                  {'title': 'Большие размеры', 'url': '#18'},
                  {'title': 'Будущие мамы', 'url': '#19'},
                  {'title': 'Для высоких', 'url': '#20'},
                  {'title': 'Для невысоких', 'url': '#21'},
                  {'title': 'Одежда для дома', 'url': '#22'},
                  {'title': 'Офис', 'url': '#23'},
                  {'title': 'Пляжная мода', 'url': '#24'},
                  {'title': 'Религиозная', 'url': '#25'},
                  {'title': 'Свадьба', 'url': '#26'},
                  {'title': 'Спецодежда и СИЗы', 'url': '#27'},
                  {'title': 'Подарки женщинам', 'url': '#28'}]},
    {'category': 'Обувь', 'data': '#shoes', 'id': 'shoes',
     'products': [{'title': 'Детская', 'url': '#1'},
                  {'title': 'Для новорожденных', 'url': '#2'},
                  {'title': 'Женская', 'url': '#3'},
                  {'title': 'Мужская', 'url': '#4'},
                  {'title': 'Ортопедическая обувь', 'url': '#5'},
                  {'title': 'Аксессуары для обуви', 'url': '#6'}]},
    {'category': 'Детям', 'data': '#kids', 'id': 'kids',
     'products': [{'title': 'Для девочек', 'url': '#1'}, {'title': 'Для мальчиков', 'url': '#2'},
                  {'title': 'Для новорожденных', 'url': '#3'}, {'title': 'Детская электроника', 'url': '#4'},
                  {'title': 'Конструкторы', 'url': '#5'}, {'title': 'Детский транспорт', 'url': '#6'},
                  {'title': 'Детское питание', 'url': '#7'}, {'title': 'Религиозная одежда', 'url': '#8'},
                  {'title': 'Товары для малыша', 'url': '#9'}, {'title': 'Подгузники', 'url': '#10'},
                  {'title': 'Подарки детям', 'url': '#11'}]},
    {'category': 'Мужчинам', 'data': '#men', 'id': 'men',
     'products': [{'title': 'Брюки', 'url': '#1'}, {'title': 'Верхняя одежда', 'url': '#2'},
                  {'title': 'Джемперы, водолазки и кардиганы', 'url': '#3'}, {'title': 'Джинсы', 'url': '#4'},
                  {'title': 'Комбинезоны и полукомбинезоны', 'url': '#5'}, {'title': 'Костюмы', 'url': '#6'},
                  {'title': 'Лонгсливы', 'url': '#7'}, {'title': 'Майки', 'url': '#8'},
                  {'title': 'Пиджаки, жилеты и жакеты', 'url': '#9'}, {'title': 'Пижамы', 'url': '#10'},
                  {'title': 'Рубашки', 'url': '#11'}, {'title': 'Толстовки, свитшоты и худи', 'url': '#12'},
                  {'title': 'Футболки', 'url': '#13'}, {'title': 'Футболки-поло', 'url': '#14'},
                  {'title': 'Халаты', 'url': '#15'}, {'title': 'Шорты', 'url': '#16'}, {'title': 'Белье', 'url': '#17'},
                  {'title': 'Большие размеры', 'url': '#18'}, {'title': 'Для высоких', 'url': '#19'},
                  {'title': 'Для невысоких', 'url': '#20'}, {'title': 'Одежда для дома', 'url': '#21'},
                  {'title': 'Офис', 'url': '#22'}, {'title': 'Пляжная одежда', 'url': '#23'},
                  {'title': 'Религиозная', 'url': '#24'}, {'title': 'Свадьба', 'url': '#25'},
                  {'title': 'Спецодежда и СИЗы', 'url': '#26'}, {'title': 'Подарки мужчинам', 'url': '#27'}]},
    {'category': 'Дом', 'data': '#house', 'id': 'house',
     'products': [{'title': 'Ванная', 'url': '#1'}, {'title': 'Кухня', 'url': '#2'},
                  {'title': 'Предметы интерьера', 'url': '#3'}, {'title': 'Спальня', 'url': '#4'},
                  {'title': 'Гостиная', 'url': '#5'}, {'title': 'Детская', 'url': '#6'},
                  {'title': 'Досуг и творчество', 'url': '#7'}, {'title': 'Все для праздника', 'url': '#8'},
                  {'title': 'Зеркала', 'url': '#9'}, {'title': 'Коврики', 'url': '#10'},
                  {'title': 'Кронштейны', 'url': '#11'}, {'title': 'Освещение', 'url': '#12'},
                  {'title': 'Для курения', 'url': '#13'}, {'title': 'Отдых на природе', 'url': '#14'},
                  {'title': 'Парфюмерия для дома', 'url': '#15'}, {'title': 'Прихожая', 'url': '#16'},
                  {'title': 'Религия, эзотерика', 'url': '#17'}, {'title': 'Сувенирная продукция', 'url': '#18'},
                  {'title': 'Хозяйственные товары', 'url': '#19'}, {'title': 'Хранение вещей', 'url': '#20'},
                  {'title': 'Цветы, вазы и кашпо', 'url': '#21'}, {'title': 'Шторы', 'url': '#22'}]},
    {'category': 'Новый год', 'data': '#newyear', 'id': 'newyear',
     'products': [{'title': 'Вечерний образ', 'url': '#1'}, {'title': 'Праздничная обувь', 'url': '#2'},
                  {'title': 'Наряды для детей', 'url': '#3'}, {'title': 'Карнавальные товары', 'url': '#4'},
                  {'title': 'Елки', 'url': '#5'}, {'title': 'Новогодний декор', 'url': '#6'},
                  {'title': 'Новогодние книги', 'url': '#7'}, {'title': 'Открытки', 'url': '#8'},
                  {'title': 'Подарки', 'url': '#9'}, {'title': 'Подарочная упаковка', 'url': '#10'},
                  {'title': 'Праздничный стол', 'url': '#11'}, {'title': 'Продукты', 'url': '#12'},
                  {'title': 'Свечи и подсвечники', 'url': '#13'}, {'title': 'Символ года', 'url': '#14'}]},
    {'category': 'Красота', 'data': '#beauty', 'id': 'beauty',
     'products': [{'title': 'Аксессуары', 'url': '#1'}, {'title': 'Волосы', 'url': '#2'},
                  {'title': 'Аптечная косметика', 'url': '#3'},
                  {'title': 'Детская декоративная косметика', 'url': '#4'}, {'title': 'Для загара', 'url': '#5'},
                  {'title': 'Для мам и малышей', 'url': '#6'}, {'title': 'Израильская косметика', 'url': '#7'},
                  {'title': 'Инструменты для парикмахеров', 'url': '#8'}, {'title': 'Корейские бренды', 'url': '#9'},
                  {'title': 'Косметические аппараты и аксессуары', 'url': '#10'},
                  {'title': 'Крымская косметика', 'url': '#11'}, {'title': 'Макияж', 'url': '#12'},
                  {'title': 'Мужская линия', 'url': '#13'}, {'title': 'Наборы для ухода', 'url': '#14'},
                  {'title': 'Ногти', 'url': '#15'}, {'title': 'Органическая косметика', 'url': '#16'},
                  {'title': 'Парфюмерия', 'url': '#17'}, {'title': 'Подарочные наборы', 'url': '#18'},
                  {'title': 'Профессиональная косметика', 'url': '#19'},
                  {'title': 'Средства личной гигиены', 'url': '#20'}, {'title': 'Гигиена полости рта', 'url': '#21'},
                  {'title': 'Уход за кожей', 'url': '#22'}]},
    {'category': 'Аксессуары', 'data': '#accessories', 'id': 'accessories',
     'products': [{'title': 'Аксессуары для волос', 'url': '#1'}, {'title': 'Аксессуары для одежды', 'url': '#2'},
                  {'title': 'Бижутерия', 'url': '#3'}, {'title': 'Веера', 'url': '#4'},
                  {'title': 'Галстуки и бабочки', 'url': '#5'}, {'title': 'Головные уборы', 'url': '#6'},
                  {'title': 'Зеркальца', 'url': '#7'}, {'title': 'Зонты', 'url': '#8'},
                  {'title': 'Кошельки и кредитницы', 'url': '#9'}, {'title': 'Маски для сна', 'url': '#10'},
                  {'title': 'Носовые платки', 'url': '#11'}, {'title': 'Очки и футляры', 'url': '#12'},
                  {'title': 'Перчатки и варежки', 'url': '#13'}, {'title': 'Платки и шарфы', 'url': '#14'},
                  {'title': 'Религиозные', 'url': '#15'}, {'title': 'Ремни и пояса', 'url': '#16'},
                  {'title': 'Сумки и рюкзаки', 'url': '#17'}, {'title': 'Часы и ремешки', 'url': '#18'},
                  {'title': 'Чемоданы и защита багажа', 'url': '#19'}]},
    {'category': 'Электроника', 'data': '#electronics', 'id': 'electronics',
     'products': [{'title': 'Автоэлектроника и навигация', 'url': '#1'}, {'title': 'Гарнитуры и наушники', 'url': '#2'},
                  {'title': 'Детская электроника', 'url': '#3'}, {'title': 'Игровые консоли и игры', 'url': '#4'},
                  {'title': 'Кабели и зарядные устройства', 'url': '#5'}, {'title': 'Музыка и видео', 'url': '#6'},
                  {'title': 'Ноутбуки и компьютеры', 'url': '#7'}, {'title': 'Офисная техника', 'url': '#8'},
                  {'title': 'Развлечения и гаджеты', 'url': '#9'}, {'title': 'Сетевое оборудование', 'url': '#10'},
                  {'title': 'Системы безопасности', 'url': '#11'}, {'title': 'Смартфоны и телефоны', 'url': '#12'},
                  {'title': 'Смарт-часы и браслеты', 'url': '#13'},
                  {'title': 'Солнечные электростанции и комплектующие', 'url': '#14'},
                  {'title': 'ТВ, аудио, фото, видео техника', 'url': '#15'},
                  {'title': 'Торговое оборудование', 'url': '#16'}, {'title': 'Умный дом', 'url': '#17'},
                  {'title': 'Электротранспорт и аксессуары', 'url': '#18'}]},
    {'category': 'Игрушки', 'data': '#toys', 'id': 'toys',
     'products': [{'title': 'Антистресс', 'url': '#1'}, {'title': 'Для малышей', 'url': '#2'},
                  {'title': 'Для песочницы', 'url': '#3'}, {'title': 'Игровые комплексы', 'url': '#4'},
                  {'title': 'Игровые наборы', 'url': '#5'}, {'title': 'Игрушечное оружие и аксессуары', 'url': '#6'},
                  {'title': 'Игрушечный транспорт', 'url': '#7'}, {'title': 'Игрушки для ванной', 'url': '#8'},
                  {'title': 'Интерактивные', 'url': '#9'}, {'title': 'Кинетический песок', 'url': '#10'},
                  {'title': 'Конструкторы', 'url': '#11'}, {'title': 'Конструкторы LEGO', 'url': '#12'},
                  {'title': 'Куклы и аксессуары', 'url': '#13'}, {'title': 'Музыкальные', 'url': '#14'},
                  {'title': 'Мыльные пузыри', 'url': '#15'}, {'title': 'Мягкие игрушки', 'url': '#16'},
                  {'title': 'Наборы для опытов', 'url': '#17'}, {'title': 'Настольные игры', 'url': '#18'},
                  {'title': 'Радиоуправляемые', 'url': '#19'}, {'title': 'Развивающие игрушки', 'url': '#20'},
                  {'title': 'Сборные модели', 'url': '#21'}, {'title': 'Спортивные игры', 'url': '#22'},
                  {'title': 'Сюжетно-ролевые игры', 'url': '#23'}, {'title': 'Творчество и рукоделие', 'url': '#24'},
                  {'title': 'Фигурки и роботы', 'url': '#25'}]},
    {'category': 'Мебель', 'data': '#furniture', 'id': 'furniture',
     'products': [{'title': 'Бескаркасная мебель', 'url': '#1'}, {'title': 'Детская мебель', 'url': '#2'},
                  {'title': 'Диваны и кресла', 'url': '#3'}, {'title': 'Столы и стулья', 'url': '#4'},
                  {'title': 'Компьютерная и геймерская мебель', 'url': '#5'},
                  {'title': 'Мебель для гостиной', 'url': '#6'}, {'title': 'Мебель для кухни', 'url': '#7'},
                  {'title': 'Мебель для прихожей', 'url': '#8'}, {'title': 'Мебель для спальни', 'url': '#9'},
                  {'title': 'Гардеробная мебель', 'url': '#10'}, {'title': 'Офисная мебель', 'url': '#11'},
                  {'title': 'Торговая мебель', 'url': '#12'}, {'title': 'Зеркала', 'url': '#13'},
                  {'title': 'Мебельная фурнитура', 'url': '#14'}]},
    {'category': 'Товары для взрослых', 'data': '#productsforadult', 'id': 'productsforadult',
     'products': [{'title': 'Белье и аксессуары', 'url': '#1'}, {'title': 'Игры и сувениры', 'url': '#2'},
                  {'title': 'Интимная косметика', 'url': '#3'}, {'title': 'Интимная съедобная косметика', 'url': '#4'},
                  {'title': 'Презервативы и лубриканты', 'url': '#5'}, {'title': 'Секс игрушки', 'url': '#6'},
                  {'title': 'Фетиш и БДСМ', 'url': '#7'}]},
    {'category': 'Продукты', 'data': '#products', 'id': 'products',
     'products': [{'title': 'Вкусные подарки', 'url': '#1'}, {'title': 'Подарочные наборы продуктов', 'url': '#2'},
                  {'title': 'Чай и кофе', 'url': '#3'}, {'title': 'Сладости и хлебобулочные изделия', 'url': '#4'},
                  {'title': 'Бакалея', 'url': '#5'}, {'title': 'Детское питание', 'url': '#6'},
                  {'title': 'Добавки пищевые', 'url': '#7'}, {'title': 'Здоровое питание', 'url': '#8'},
                  {'title': 'Мясная продукция', 'url': '#9'}, {'title': 'Молочные продукты', 'url': '#10'},
                  {'title': 'Напитки', 'url': '#11'}, {'title': 'Снеки', 'url': '#12'},
                  {'title': 'Смеси для десертов', 'url': '#13'}, {'title': 'Фрукты и ягоды', 'url': '#14'},
                  {'title': 'Овощи', 'url': '#15'}]},
    {'category': 'Бытовая техника', 'data': '#appliances', 'id': 'appliances',
     'products': [{'title': 'Климатическая техника', 'url': '#1'}, {'title': 'Красота и здоровье', 'url': '#2'},
                  {'title': 'Садовая техника', 'url': '#3'}, {'title': 'Техника для дома', 'url': '#4'},
                  {'title': 'Техника для кухни', 'url': '#5'}, {'title': 'Крупная бытовая техника', 'url': '#6'}]},
    {'category': 'Зоотовары', 'data': '#zoo', 'id': 'zoo',
     'products': [{'title': 'Для кошек', 'url': '#1'}, {'title': 'Для собак', 'url': '#2'},
                  {'title': 'Для птиц', 'url': '#3'}, {'title': 'Для грызунов и хорьков', 'url': '#4'},
                  {'title': 'Для лошадей', 'url': '#5'}, {'title': 'Аквариумистика', 'url': '#6'},
                  {'title': 'Террариумистика', 'url': '#7'}, {'title': 'Фермерство', 'url': '#8'},
                  {'title': 'Корм и лакомства', 'url': '#9'}, {'title': 'Аксессуары для кормления', 'url': '#10'},
                  {'title': 'Лотки и наполнители', 'url': '#11'}, {'title': 'Когтеточки и домики', 'url': '#12'},
                  {'title': 'Транспортировка', 'url': '#13'}, {'title': 'Амуниция и дрессировка', 'url': '#14'},
                  {'title': 'Игрушки', 'url': '#15'}, {'title': 'Груминг и уход', 'url': '#16'},
                  {'title': 'Одежда', 'url': '#17'}, {'title': 'Ветаптека', 'url': '#18'}]},
    {'category': 'Спорт', 'data': '#sport', 'id': 'sport',
     'products': [{'title': 'Фитнес и тренажеры', 'url': '#1'}, {'title': 'Велоспорт', 'url': '#2'},
                  {'title': 'Йога, пилатес', 'url': '#3'}, {'title': 'Охота и рыбалка', 'url': '#4'},
                  {'title': 'Самокаты, ролики, скейтборды', 'url': '#5'}, {'title': 'Туризм, походы', 'url': '#6'},
                  {'title': 'Бег, ходьба', 'url': '#7'}, {'title': 'Командные виды спорта', 'url': '#8'},
                  {'title': 'Водные виды спорта', 'url': '#9'}, {'title': 'Зимние виды спорта', 'url': '#10'},
                  {'title': 'Поддержка и восстановление', 'url': '#11'},
                  {'title': 'Спортивное питание и косметика', 'url': '#12'},
                  {'title': 'Бадминтон, теннис', 'url': '#13'},
                  {'title': 'Бильярд, гольф, дартс, метание ножей', 'url': '#14'},
                  {'title': 'Единоборства', 'url': '#15'}, {'title': 'Конный спорт', 'url': '#16'},
                  {'title': 'Мотоспорт', 'url': '#17'}, {'title': 'Оборудование для сдачи нормативов', 'url': '#18'},
                  {'title': 'Парусный спорт', 'url': '#19'}, {'title': 'Скалолазание, альпинизм', 'url': '#20'},
                  {'title': 'Страйкбол и пейнтбол', 'url': '#21'}, {'title': 'Танцы, гимнастика', 'url': '#22'},
                  {'title': 'Для детей', 'url': '#23'}, {'title': 'Для женщин', 'url': '#24'},
                  {'title': 'Для мужчин', 'url': '#25'}, {'title': 'Спортивная обувь', 'url': '#26'},
                  {'title': 'Товары для самообороны', 'url': '#27'}, {'title': 'Электроника', 'url': '#28'}]},
    {'category': 'Автотовары', 'data': '#autoproducts', 'id': 'autoproducts',
     'products': [{'title': 'Запчасти на легковые автомобили', 'url': '#1'}, {'title': 'Масла и жидкости', 'url': '#2'},
                  {'title': 'Автокосметика и автохимия', 'url': '#3'}, {'title': 'Краски и грунтовки', 'url': '#4'},
                  {'title': 'Автоэлектроника и навигация', 'url': '#5'},
                  {'title': 'Аксессуары в салон и багажник', 'url': '#6'}, {'title': 'Коврики', 'url': '#7'},
                  {'title': 'Внешний тюнинг', 'url': '#8'},
                  {'title': 'Другие аксессуары и доп. оборудование', 'url': '#9'},
                  {'title': 'Шины и диски колесные', 'url': '#10'}, {'title': 'Инструменты', 'url': '#11'},
                  {'title': 'Мойки высокого давления и аксессуары', 'url': '#12'},
                  {'title': 'Мототовары', 'url': '#13'}, {'title': 'OFFroad', 'url': '#14'},
                  {'title': 'Запчасти на силовую технику', 'url': '#15'},
                  {'title': 'Запчасти для лодок и катеров', 'url': '#16'}]},
    {'category': 'Книги', 'data': '#books', 'id': 'books',
     'products': [{'title': 'Художественная литература', 'url': '#1'}, {'title': 'Комиксы и манга', 'url': '#2'},
                  {'title': 'Книги для детей', 'url': '#3'}, {'title': 'Воспитание и развитие ребенка', 'url': '#4'},
                  {'title': 'Образование', 'url': '#5'}, {'title': 'Самообразование и развитие', 'url': '#6'},
                  {'title': 'Бизнес и менеджмент', 'url': '#7'}, {'title': 'Хобби и досуг', 'url': '#8'},
                  {'title': 'Астрология и эзотерика', 'url': '#9'}, {'title': 'Дом, сад и огород', 'url': '#10'},
                  {'title': 'Красота, здоровье и спорт', 'url': '#11'},
                  {'title': 'Научно-популярная литература', 'url': '#12'},
                  {'title': 'Интернет и технологии', 'url': '#13'},
                  {'title': 'Литературоведение и публицистика', 'url': '#14'},
                  {'title': 'Историческая и военная литература', 'url': '#15'}, {'title': 'Философия', 'url': '#16'},
                  {'title': 'Религия', 'url': '#17'}, {'title': 'Политика и право', 'url': '#18'},
                  {'title': 'Букинистика', 'url': '#19'}, {'title': 'Книги на иностранных языках', 'url': '#20'},
                  {'title': 'Плакаты', 'url': '#21'}, {'title': 'Календари', 'url': '#22'},
                  {'title': 'Коллекционные издания', 'url': '#23'}, {'title': 'Репринтные издания', 'url': '#24'},
                  {'title': 'Мультимедиа', 'url': '#25'}, {'title': 'Аудиокниги', 'url': '#26'}]},
    {'category': 'Для ремонта', 'data': '#forrepair', 'id': 'forrepair',
     'products': [{'title': 'Двери, окна и фурнитура', 'url': '#1'}, {'title': 'Инструменты и оснастка', 'url': '#2'},
                  {'title': 'Отделочные материалы', 'url': '#3'}, {'title': 'Электрика', 'url': '#4'},
                  {'title': 'Лакокрасочные материалы', 'url': '#5'},
                  {'title': 'Сантехника, отопление и газоснабжение', 'url': '#6'}, {'title': 'Вентиляция', 'url': '#7'},
                  {'title': 'Крепеж', 'url': '#8'}, {'title': 'Стройматериалы', 'url': '#9'}]},
    {'category': 'Сад и дача', 'data': '#garden', 'id': 'garden',
     'products': [{'title': 'Растения, семена и грунты', 'url': '#1'},
                  {'title': 'Горшки, опоры и все для рассады', 'url': '#2'},
                  {'title': 'Удобрения, химикаты и средства защиты', 'url': '#3'},
                  {'title': 'Товары для бани и сауны', 'url': '#4'}, {'title': 'Грили, мангалы и барбекю', 'url': '#5'},
                  {'title': 'Теплицы, парники, укрывной материал', 'url': '#6'},
                  {'title': 'Мойки высокого давления и аксессуары', 'url': '#7'},
                  {'title': 'Садовая техника', 'url': '#8'}, {'title': 'Садовый инструмент', 'url': '#9'},
                  {'title': 'Полив и водоснабжение', 'url': '#10'},
                  {'title': 'Товары для кемпинга, пикника и отдыха', 'url': '#11'},
                  {'title': 'Садовый декор', 'url': '#12'}, {'title': 'Садовая мебель', 'url': '#13'},
                  {'title': 'Надувная мебель', 'url': '#14'},
                  {'title': 'Дачные умывальники, души и туалеты', 'url': '#15'}, {'title': 'Бассейны', 'url': '#16'},
                  {'title': 'Защита от насекомых и грызунов', 'url': '#17'}]},
    {'category': 'Здоровье', 'data': '#healt', 'id': 'healt',
     'products': [{'title': 'Дезинфекция, стерилизация и утилизация', 'url': '#1'},
                  {'title': 'Ухо, горло, нос', 'url': '#2'}, {'title': 'Контрацептивы и лубриканты', 'url': '#3'},
                  {'title': 'Маски защитные', 'url': '#4'}, {'title': 'Медицинские изделия', 'url': '#5'},
                  {'title': 'Медицинские приборы', 'url': '#6'}, {'title': 'Оздоровление', 'url': '#7'},
                  {'title': 'Оптика', 'url': '#8'}, {'title': 'Сиропы и бальзамы', 'url': '#9'},
                  {'title': 'Уход за полостью рта', 'url': '#10'}]},
    {'category': 'Канцтовары', 'data': '#stationery', 'id': 'stationery',
     'products': [{'title': 'Анатомические модели', 'url': '#1'}, {'title': 'Бумажная продукция', 'url': '#2'},
                  {'title': 'Карты и глобусы', 'url': '#3'}, {'title': 'Офисные принадлежности', 'url': '#4'},
                  {'title': 'Письменные принадлежности', 'url': '#5'}, {'title': 'Рисование и лепка', 'url': '#6'},
                  {'title': 'Счетный материал', 'url': '#7'}, {'title': 'Торговые принадлежности', 'url': '#8'},
                  {'title': 'Чертежные принадлежности', 'url': '#9'}]},
    {'category': 'Акции', 'data': '#promotions', 'id': 'promotions',
     'products': [{'title': 'Товары с местного склада', 'url': '#1'}, {'title': 'Скидки до -90%', 'url': '#2'},
                  {'title': 'Клиентские дни', 'url': '#3'}]},
]
navbar_list = [
    {'title': 'Доставки', 'img': 'products/images/header/delivery.png', 'alt': 'delivery',
     'href': 'products:delivery'},
    {'title': 'Избранное', 'img': 'products/images/header/favorites.png', 'alt': 'favorite',
     'href': 'products:favourites'},
    {'title': 'Профиль', 'img': 'products/images/header/profile.png', 'alt': 'profile', 'href': 'products:profile'},
    {'title': 'Корзина', 'img': 'products/images/header/basket.png', 'alt': 'basket', 'href': 'products:shopping_cart'},
]
footer_list = [
    {'title': 'Покупателям',
     'description': [{'title': 'Способы оплаты', 'url': 'products:payment_methods'},
                     {'title': 'Возврат товара', 'url': 'products:item_return'},
                     {'title': 'Правила продажи товаров', 'url': 'products:sale_rules'},
                     {'title': 'Правила доставки', 'url': 'products:delivery_rules'},
                     {'title': 'Возврат денежных средств', 'url': 'products:money_return'},
                     {'title': 'Правила пользования торговой площадкой', 'url': 'products:terms_rules'},
                     {'title': 'Политика обработки персональных данных', 'url': 'products:policy'},
                     ]},
    {'title': 'Партнерам', 'description': [{'title': 'Продавайте на StuffStore', 'url': 'products:sale_on_market'},
                                           {'title': 'Партнерский пункт выдачи', 'url': 'products:point_promo'},
                                           {'title': 'Франшизный пункт выдачи', 'url': 'products:franchisee'}]},
    {'title': 'Проекты', 'description': [{'title': 'WB Guru', 'url': 'products:guru'},
                                            {'title': 'Трудоустройство', 'url': 'products:all_work'},
                                            {'title': 'Цифровые товары', 'url': 'products:digital'}]},
    {'title': 'Компания', 'description': [{'title': 'О нас', 'url': 'products:about_us'},
                                          {'title': 'Контакты', 'url': 'products:contacts'},
                                          {'title': 'Вакансии', 'url': 'products:vacancies'}]},
]

cards = [{'id': 1, 'title': 'Карточка 1 с длинным названием',
          'images_url': ['/media/images/cards/1.jpg', 'media/images/cards/2.jpg', 'media/images/cards/7.png'],
          'price': 10, 'count_of_reviews': 12, 'avg_reviews': 4},
         {'id': 2, 'title': 'Карточка 3',
          'images_url': ['/media/images/cards/3.jpg', '/media/images/cards/2.jpg', '/media/images/cards/7.png'],
          'price': 32, 'count_of_reviews': 35, 'avg_reviews': 2},
         {'id': 3, 'title': 'Карточка 2',
          'images_url': ['/media/images/cards/2.jpg', '/media/images/cards/2.jpg', '/media/images/cards/7.png'],
          'price': 101, 'count_of_reviews': 1, 'avg_reviews': 3},
         {'id': 4, 'title': 'Карточка 4',
          'images_url': ['/media/images/cards/4.jpg', '/media/images/cards/2.jpg', 'media/images/cards/7.png'],
          'price': 66, 'count_of_reviews': 88, 'avg_reviews': 1},
         {'id': 5, 'title': 'Карточка 5',
          'images_url': ['/media/images/cards/5.jpg', '/media/images/cards/2.jpg', '/media/images/cards/1.jpg'],
          'price': 19, 'count_of_reviews': 11111, 'avg_reviews': 1.5},
         {'id': 6, 'title': 'Карточка 6',
          'images_url': ['/media/images/cards/6.jpg', '/media/images/cards/2.jpg', '/media/images/cards/7.png'],
          'price': 999, 'count_of_reviews': 2222, 'avg_reviews': 4.6},
         {'id': 7, 'title': 'Карточка 7',
          'images_url': ['/media/images/cards/7.png', '/media/images/cards/2.jpg', '/media/images/cards/7.png'],
          'price': 4, 'count_of_reviews': 676767, 'avg_reviews': 4.9},
         {'id': 8, 'title': 'Карточка 8',
          'images_url': ['/media/images/cards/8.png', '/media/images/cards/2.jpg', '/media/images/cards/1.jpg'],
          'price': 74, 'count_of_reviews': 234, 'avg_reviews': 1.9},
         {'id': 9, 'title': 'Карточка 9',
          'images_url': ['/media/images/cards/9.jpg', '/media/images/cards/2.jpg', '/media/images/cards/7.png'],
          'price': 88, 'count_of_reviews': 1, 'avg_reviews': 5},
         {'id': 10, 'title': 'Карточка 10',
          'images_url': ['/media/images/cards/1.jpg', '/media/images/cards/2.jpg', '/media/images/cards/7.png'],
          'price': 98, 'count_of_reviews': 99, 'avg_reviews': 4.1},
         ]

favourite_cards = [{'id': 1, 'title': 'Карточка 1 с длинным названием',
                    'images_url': ['/media/images/cards/1.jpg', '/media/images/cards/2.jpg',
                                   '/media/images/cards/7.png'], 'price': 10, 'count_of_reviews': 12, 'avg_reviews': 4},
                   {'id': 2, 'title': 'Карточка 3',
                    'images_url': ['/media/images/cards/3.jpg', '/media/images/cards/2.jpg',
                                   '/media/images/cards/7.png'], 'price': 32, 'count_of_reviews': 35, 'avg_reviews': 2},
                   {'id': 3, 'title': 'Карточка 2',
                    'images_url': ['/media/images/cards/2.jpg', '/media/images/cards/2.jpg',
                                   '/media/images/cards/7.png'], 'price': 101, 'count_of_reviews': 1, 'avg_reviews': 3},
                   {'id': 4, 'title': 'Карточка 4',
                    'images_url': ['/media/images/cards/4.jpg', '/media/images/cards/2.jpg',
                                   '/media/images/cards/7.png'], 'price': 66, 'count_of_reviews': 88, 'avg_reviews': 1},
                   ]

shopping_cards = [
    {'id': 1, 'title': 'Карточка 1 с длинным названием', 'image_url': '/media/images/cards/1.jpg', 'price': 10,
     'count_of_reviews': 12, 'avg_reviews': 4},
    {'id': 2, 'title': 'Карточка 3', 'image_url': '/media/images/cards/3.jpg', 'price': 32, 'count_of_reviews': 35,
     'avg_reviews': 2},
    {'id': 3, 'title': 'Карточка 2', 'image_url': '/media/images/cards/2.jpg', 'price': 101, 'count_of_reviews': 1,
     'avg_reviews': 3},
    {'id': 4, 'title': 'Карточка 4', 'image_url': '/media/images/cards/4.jpg', 'price': 66, 'count_of_reviews': 88,
     'avg_reviews': 1},
    ]

payment_list = [
    {'img': 'products/images/footer/visa.png', 'alt': 'visa'},
    {'img': 'products/images/footer/visa-secure.png', 'alt': 'visa-secure'},
    {'img': 'products/images/footer/mastercard.png', 'alt': 'mastercard'},
    {'img': 'products/images/footer/mastercard-secure.png', 'alt': 'mastercard-secure'},
    {'img': 'products/images/footer/mastercard-securecode.png', 'alt': 'mastercard-securecode'},
    {'img': 'products/images/footer/belkart-slogan.png', 'alt': 'belkart-slogan'},
    {'img': 'products/images/footer/belkart-internet-password.png', 'alt': 'belkart-internet-password'},
    {'img': 'products/images/footer/mir-new.png', 'alt': 'mir-new'},
    {'img': 'products/images/footer/mir-accept.png', 'alt': 'mir-accept'},
    {'img': 'products/images/footer/webpay.png', 'alt': 'webpay'},
]

user_reviews = [
    {'id': 1, 'title': 'Карточка 1 с длинным названием', 'image_url': '/media/images/cards/1.jpg', 'stars': range(5),
     'review': 'Очень хорошо чистит трубы', 'date': '28 янв.'},
    {'id': 2, 'title': 'Карточка 2', 'image_url': '/media/images/cards/2.jpg', 'stars': range(2),
     'review': 'Плохо чистит трубы', 'date': '23 янв.'},
    {'id': 3, 'title': 'Карточка 3', 'image_url': '/media/images/cards/2.jpg', 'stars': range(4),
     'review': 'Добрый день! Спасибо за покупку! Очень рады, что Вам понравился ночник Луна. Пользуйтесь с удовольствием! С уважением и наилучшими пожеланиями, Magic Blanc!',
     'date': '1 янв. 2022 г.'},
    {'id': 4, 'title': 'Карточка 3', 'image_url': '/media/images/cards/2.jpg', 'stars': range(4), 'review': '',
     'date': '1 янв. 2022 г.'},
    {'id': 5, 'title': 'Карточка 3', 'image_url': '/media/images/cards/2.jpg', 'stars': range(4),
     'review': 'Добрый день! Спасибо за покупку! Очень рады, что Вам понравился ночник Луна. Пользуйтесь с удовольствием! С уважением и наилучшими пожеланиями, Magic Blanc!',
     'date': '1 янв. 2022 г.'},
]
