# Generated by Django 5.0.1 on 2024-03-26 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='basket_history',
            field=models.JSONField(default=0),
        ),
    ]
