# Generated by Django 5.0.1 on 2024-03-26 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_basket_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='basket_history',
        ),
    ]
