# Generated by Django 5.0.1 on 2024-04-08 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_basket_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='basket_history',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Создан'), (1, 'Оплачен'), (2, 'В пути'), (3, 'Доставлен'), (4, 'Получено')], default=0),
        ),
    ]
