# Generated by Django 5.0.1 on 2024-03-20 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0006_alter_basket_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='basket',
            managers=[
            ],
        ),
    ]
