# Generated by Django 5.0.1 on 2024-02-06 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='data',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='id_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
