# Generated by Django 5.0.1 on 2024-02-10 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_data_category_id_name'),
        ('products', '0002_category_slug_subcategory_slug'),
    ]

    operations = [
    ]
