# Generated by Django 5.0.1 on 2024-02-10 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_merge_20240210_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='data',
        ),
        migrations.RemoveField(
            model_name='category',
            name='id_name',
        ),
    ]
