# Generated by Django 5.0.1 on 2024-03-15 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_categorydetails_alter_details_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='product',
            name='review',
        ),
    ]
